version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: ./dockerfiles/front/Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  back:
    build:
      context: .
      dockerfile: ./dockerfiles/back/Dockerfile
      args:
        # Set in os environment using `export XDEBUG_CLIENT_HOST=$(ip addr show docker0 | grep -Po 'inet \K[\d.]+')` for linux and WSL2
        # or `export XDEBUG_CLIENT_HOST=host.docker.internal` for mac and windows Docker Desktop
        XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_KEY: base64:FvZbGD3zL1gz/aTB0ZVf6nz0JsWRdW5DSL5LwzWacxQ= # Generate with `php -r "echo base64_encode(random_bytes(32));"`
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: chatbotto
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    expose:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./dockerfiles/db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chatbotto
    ports:
      - "5432:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
